### ISSUE TITLE
Paramètre pour choisir entre gCO2 ou kgCO2 (par défaut)

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport-api#3]

**Comment by florianpanchout** [comment]
On a maintenant les g, kg et t directement dans la réponse. Pour la requête de Fnac/Darty, ils peuvent appeler : 

https://api.monimpacttransport.fr/beta/getEmissionsPerDistance?transportations=4,7,9&km=3

ce qui leur donnera les valeurs pour la voiture, le bus et le vélo (qui sont les 3 véhicules qu'ils souhaitent afficher dans leur widget si j'ai bien suivi)
